### ISSUE TITLE
When adding null to a string it sometimes throws a compile-time exception

### ISSUE THREAD

**Issue by dplassgit** [dplassgit/d2lang#221]

**Comment by dplassgit** [comment]
```
Exception in thread "main" java.lang.NullPointerException
        at com.plasstech.lang.d2.optimize.ArithmeticOptimizer.optimizeAdd(ArithmeticOptimizer.java:530)
        at com.plasstech.lang.d2.optimize.ArithmeticOptimizer.visit(ArithmeticOptimizer.java:145)
        at com.plasstech.lang.d2.codegen.il.BinOp.accept(BinOp.java:46)
        at com.plasstech.lang.d2.optimize.LineOptimizer.optimize(LineOptimizer.java:56)
        at com.plasstech.lang.d2.optimize.ILOptimizer.optimize(ILOptimizer.java:76)
        at com.plasstech.lang.d2.optimize.ILOptimizer.execute(ILOptimizer.java:57)
        at com.plasstech.lang.d2.D2Compiler.main(D2Compiler.java:76)
```

**Comment by dplassgit** [comment]
And also someimtes it adds the string "null" to the string.

**Comment by dplassgit** [comment]
And with no optimization it throws a different exception

```
Exception in thread "main" java.lang.NullPointerException
        at com.plasstech.lang.d2.codegen.StringCodeGenerator.generateStringLength(StringCodeGenerator.java:494)
        at com.plasstech.lang.d2.codegen.StringCodeGenerator.generateStringAdd(StringCodeGenerator.java:400)
        at com.plasstech.lang.d2.codegen.NasmCodeGenerator.visit(NasmCodeGenerator.java:315)
        at com.plasstech.lang.d2.codegen.il.BinOp.accept(BinOp.java:46)
        at com.plasstech.lang.d2.codegen.NasmCodeGenerator.execute(NasmCodeGenerator.java:158)
        at com.plasstech.lang.d2.D2Compiler.main(D2Compiler.java:86)
```
