### ISSUE TITLE
Allow symbols with a leading underscore _

### ISSUE THREAD

**Issue by dplassgit** [dplassgit/d2lang#321]
There's really no good reason to reject them. 

When translating user-created symbols (proc names, globals) into memory storage, the code generators can prepend an underscore.

For internal-only symbols (e.g., internal labels), the code generator(s) can prepend D_. This way, internal symbols will never start with an underscore and external ones will always. If the user prepends their own underscore, the compiler will just prepend another one.

This is also needed for external procs that start with an underscore (!).

**Comment by dplassgit** [comment]
This is broken:

```
D_longtemp_0=[1]
print D_longtemp_0[0]
```

gives a compile-time error when a longtemp named `D_longtemp_0` is created by the compiler:

```
java.lang.IllegalStateException: D_longtemp_0 already declared as D_longtemp_0: 1-d ARRAY of INT. Cannot be redeclared as 1-d ARRAY of INT.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:853)
	at com.plasstech.lang.d2.type.SymbolTable.declareVariable(SymbolTable.java:246)
	at com.plasstech.lang.d2.type.SymbolTable.declareTemp(SymbolTable.java:136)
	at com.plasstech.lang.d2.codegen.ILCodeGenerator.allocateLongTemp(ILCodeGenerator.java:123)
	at com.plasstech.lang.d2.codegen.ILCodeGenerator.visit(ILCodeGenerator.java:236)
	at com.plasstech.lang.d2.parse.node.ArrayLiteralNode.accept(ArrayLiteralNode.java:31)
	at com.plasstech.lang.d2.codegen.ILCodeGenerator.visit(ILCodeGenerator.java:268)
	at com.plasstech.lang.d2.parse.node.AssignmentNode.accept(AssignmentNode.java:29)
	at com.plasstech.lang.d2.parse.node.DefaultNodeVisitor.lambda$1(DefaultNodeVisitor.java:33)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at com.plasstech.lang.d2.parse.node.DefaultNodeVisitor.visit(DefaultNodeVisitor.java:33)
	at com.plasstech.lang.d2.codegen.ILCodeGenerator.visit(ILCodeGenerator.java:685)
	at com.plasstech.lang.d2.parse.node.BlockNode.accept(BlockNode.java:38)
	at com.plasstech.lang.d2.parse.node.DefaultNodeVisitor.visit(DefaultNodeVisitor.java:9)
	at com.plasstech.lang.d2.parse.node.ProgramNode.accept(ProgramNode.java:18)
	at com.plasstech.lang.d2.codegen.ILCodeGenerator.generate(ILCodeGenerator.java:103)
	at com.plasstech.lang.d2.codegen.ILCodeGenerator.execute(ILCodeGenerator.java:95)
	at com.plasstech.lang.d2.YetAnotherCompiler.compile(YetAnotherCompiler.java:41)
	at com.plasstech.lang.d2.codegen.x64.testing.ExecutionSubject.executes(ExecutionSubject.java:109)
	at com.plasstech.lang.d2.codegen.x64.testing.ExecutionSubject.executedEqualsInterpreted(ExecutionSubject.java:88)
	at com.plasstech.lang.d2.codegen.x64.testing.ExecutionSubject.executedEqualsInterpreted(ExecutionSubject.java:103)
	at com.plasstech.lang.d2.codegen.x64.NasmCodeGeneratorArrayTest.arrayOpAssign(NasmCodeGeneratorArrayTest.java:175)
```
